parameters:
- name: skipTaskX
  type: string
  default: 'False'
- name: skipTaskY
  type: string
  default: 'False'

jobs:
  - job: TEMPLATE
    variables:
      skipTaskXVar: ${{ parameters.skipTaskX }}
      skipTaskYVar: ${{ parameters.skipTaskY }}
    steps:
    - script: echo "In Template"
    - script: echo "Task X"
      condition: ne(variables.skipTaskXVar, 'True')
    - script: echo "Task Y"
      condition: ne(variables.skipTaskYVar, 'True')
