parameters:
- name: skipTaskX
  type: string
  default: 'False'
- name: skipTaskY
  type: string
  default: 'False'

jobs:
  - job: TEMPLATE
    variables:
      skipTaskX: ${{ skipTaskX }}
      skipTaskY: ${{ skipTaskY }}
    steps:
    - script: echo "In Template"
    - script: echo "Task X"
      condition: not(skipTaskX)
    - script: echo "Task Y"
      condition: not(skipTaskY)
